---
- name: Configure VM hardware (CPU and memory)
  vmware_guest:
    hostname: "{{ vmware_host }}"
    username: "{{ vmware_user }}"
    password: "{{ vmware_password }}"
    validate_certs: no
    name: "{{ vm_name }}"
    datacenter: "{{ vmware_datacenter }}"
    hardware:
      memory_mb: "{{ vm_memory_mb }}"
      num_cpus: "{{ vm_num_cpus }}"
      scsi: paravirtual
    state: present
  delegate_to: localhost
  register: config_hw_result

- name: "Configure C: Drive (300 GB)"
  vmware_guest_disk:
    hostname: "{{ vmware_host }}"
    username: "{{ vmware_user }}"
    password: "{{ vmware_password }}"
    validate_certs: no
    datacenter: "{{ vmware_datacenter }}"
    name: "{{ vm_name }}"
    disk:
      - size_gb: "{{ vm_disk_c_size_gb }}"
        scsi_controller: 0
        unit_number: 0
        state: present
        type: thin
  delegate_to: localhost
  register: config_disk_c_result

- name: "Configure D: Drive (200 GB)"
  vmware_guest_disk:
    hostname: "{{ vmware_host }}"
    username: "{{ vmware_user }}"
    password: "{{ vmware_password }}"
    validate_certs: no
    datacenter: "{{ vmware_datacenter }}"
    name: "{{ vm_name }}"
    disk:
      - size_gb: "{{ vm_disk_d_size_gb }}"
        scsi_controller: 0
        unit_number: 1
        state: present
        type: thin
  delegate_to: localhost
  register: config_disk_d_result
