---
- name: Check host reachability
  hosts: "{{ ansible_limit | default(omit) }}" # Allows limiting hosts dynamically
  gather_facts: false
  tasks:
    - name: host recheability
      block:
        - name: check connection of the server
          ansible.builtin.setup:
          register: reachable_check
          ignore_errors: true  # Ignore errors to continue playbook execution
        - name:  Add to un/reachable hosts
          ansible.builtin.group_by:
            key: "{{ (reachable_check.failed | default(false)) | ternary('unreachable', 'reachable') }}_hosts"

- name: Windows Server DEPLOYMENT
  hosts: reachable_hosts

  roles:
    - role: pack_prometheus_node_exporter
      tags: prometheus_node_exporter
      when: (pack_prometheus_node_exporter_enabled | default(false))
